# ------------------------------------------------------------------
# Recursive-IR configuration file
# Copyright (c) 2026 Mark Jayson Alvarez
# Licensed under the Recursive-IR License
#
# ------------------------------------------------------------------
# Global Filebeat config (no inputs here)
filebeat.config.inputs:
  enabled: true
  path: ${path.config}/inputs.d/*.yml
  reload.enabled: true
  reload.period: 2s
  scan.frequency: 1s

# ---- Output: Logstash (beats input on 5044) ----
output.logstash:
  hosts: ["127.0.0.1:15044"]
  # ssl:
  #   certificate_authorities: ["/etc/ssl/certs/improvisec-root-ca.pem"]

# Paths (match what your logs show)
path.home: /usr/share/recursive-ir/filebeat
path.config: /etc/recursive-ir/filebeat
path.data: /var/lib/recursive-ir/filebeat
path.logs: /var/log/recursive-ir/filebeat

logging.to_files: true
logging.files:
  path: /var/log/recursive-ir/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644


