services:
  nginx:
    image: nginx:1.27-alpine
    container_name: recursive-ir-nginx
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - recursive-ir-api
      - recursive-ir-ui

  recursive-ir-api:
    image: ghcr.io/improvisec/recursive-ir-api:${RI_TAG:-latest}
    container_name: recursive-ir-api
    network_mode: host
    restart: unless-stopped
    user: "${RI_UID}:${RI_GID}"
    volumes:
      - type: bind
        source: /var/lib/recursive-ir/web
        target: /data
        bind:
          create_host_path: false
      - type: bind
        source: /etc/recursive-ir/logstash/certs
        target: /etc/recursive-ir/logstash/certs
        read_only: true
      - type: bind
        source: /etc/recursive-ir/conf/tags
        target: /etc/recursive-ir/conf/tags
        read_only: true
        bind:
          create_host_path: false
    env_file:
      - /etc/recursive-ir/conf/recursive.env

  recursive-ir-ui:
    image: ghcr.io/improvisec/recursive-ir-ui:${RI_TAG:-latest}
    container_name: recursive-ir-ui
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:80"
